// Self-contained HTML report builders, rendered to PDF by the main process via
// Electron's printToPDF. No external assets, no dependency, no persistence.
//
// AMBIGUITY FIDELITY (required): any field carrying ambiguity/confidence
// metadata is styled distinctly here so it can NEVER render identically to a
// confident value in the exported PDF — the artifact most likely to leave the
// app and reach a third party. Ambiguous cells get a tinted background, an
// inline "⚠ ambiguous" marker, and the note printed beneath the value.

import { extractTables } from './tableExport.js'

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;')
}

// Shared, print-optimized document shell. Dark ink on white (print-safe), with
// the paper/taupe accent for headings.
function reportShell(title, subtitle, bodyHtml) {
  const generated = new Date().toLocaleString()
  return `<!doctype html>
<html><head><meta charset="utf-8">
<style>
  @page { size: A4; margin: 18mm 16mm; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; color: #1f1d1d; margin: 0; font-size: 12px; line-height: 1.5; }
  .rpt-head { border-bottom: 2px solid #1f1d1d; padding-bottom: 10px; margin-bottom: 18px; }
  .rpt-brand { font-size: 12px; font-weight: 700; letter-spacing: -0.02em; }
  .rpt-brand .dot { color: #b3a798; }
  .rpt-title { font-size: 22px; font-weight: 600; letter-spacing: -0.02em; margin: 6px 0 2px; }
  .rpt-sub { font-size: 12px; color: #665f56; }
  .rpt-meta { font-size: 10px; color: #968c80; margin-top: 6px; }
  table { border-collapse: collapse; width: 100%; margin: 8px 0 14px; font-size: 11px; }
  th { background: #f2ede6; text-align: left; padding: 7px 9px; border: 1px solid #d8d0c4; font-size: 9.5px; text-transform: uppercase; letter-spacing: 0.05em; color: #1f1d1d; }
  td { padding: 7px 9px; border: 1px solid #e4ddd1; vertical-align: top; }
  td.missing { color: #968c80; }
  td.ambiguous { background: rgba(217,119,87,0.10); color: #a0543a; }
  td.ambiguous .flag { display: inline-block; margin-left: 6px; font-size: 8.5px; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 700; }
  td.ambiguous .note { font-size: 9px; color: #a0543a; margin-top: 3px; }
  .src { font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: 10px; color: #665f56; }
  .ans p { margin: 0 0 9px; }
  .ans strong { font-weight: 700; }
  .cites { margin-top: 16px; border-top: 1px dashed #b3a798; padding-top: 10px; }
  .cites-h { font-size: 9.5px; text-transform: uppercase; letter-spacing: 0.08em; color: #b3a798; margin-bottom: 6px; }
  .cite { font-family: ui-monospace, Menlo, monospace; font-size: 10px; color: #1f1d1d; margin: 2px 0; }
  .rpt-foot { margin-top: 22px; border-top: 1px dashed #d8d0c4; padding-top: 8px; font-size: 9px; color: #968c80; }
  .legend { font-size: 9px; color: #a0543a; margin-top: 4px; }
</style></head>
<body>
  <div class="rpt-head">
    <div class="rpt-brand">rudo<span class="dot">.</span></div>
    <div class="rpt-title">${esc(title)}</div>
    ${subtitle ? `<div class="rpt-sub">${esc(subtitle)}</div>` : ''}
    <div class="rpt-meta">Generated ${esc(generated)} · on-device</div>
  </div>
  ${bodyHtml}
  <div class="rpt-foot">Generated by Rudo — your documents, one honest assistant away. Fields marked “⚠ ambiguous” were preserved exactly as written and require review.</div>
</body></html>`
}

function cellHtml(cell) {
  if (!cell || cell.status === 'MISSING') return `<td class="missing">—</td>`
  if (cell.status === 'AMBIGUOUS') {
    return `<td class="ambiguous">${esc(cell.value)}<span class="flag">⚠ ambiguous</span>` +
      `${cell.note ? `<div class="note">${esc(cell.note)}</div>` : ''}</td>`
  }
  return `<td>${esc(cell.value)}</td>`
}

function findCell(row, name) {
  return (row.cells || []).find(c => c.name === name)
}

function hasAnyAmbiguity(rows) {
  return (rows || []).some(r => (r.cells || []).some(c => c.status === 'AMBIGUOUS'))
}

// ── Extraction Report / Client Summary (structured table) ───────────────────
export function buildExtractionReport({ title, subtitle, columns, rows }) {
  const head = `<tr>${columns.map(c => `<th>${esc(c.name)}</th>`).join('')}<th>Source</th></tr>`
  const body = (rows || []).map(r => {
    const cells = columns.map(col => cellHtml(findCell(r, col.name))).join('')
    return `<tr>${cells}<td class="src">${esc(r.fileName)}</td></tr>`
  }).join('')
  const legend = hasAnyAmbiguity(rows)
    ? `<div class="legend">⚠ ambiguous = value preserved exactly as written; interpretation uncertain — review before relying on it.</div>` : ''
  const table = `<table><thead>${head}</thead><tbody>${body}</tbody></table>${legend}`
  return reportShell(title || 'Extraction Report',
    subtitle || `${(rows || []).length} document(s)`, table)
}

// ── Bulk Q&A Report (Document | Answer | Source) ────────────────────────────
export function buildBulkQaReport({ title, question, rows }) {
  const answerCol = (rows[0]?.cells?.[0]?.name) || 'Answer'
  const head = `<tr><th>Document</th><th>${esc(answerCol)}</th><th>Source</th></tr>`
  const body = (rows || []).map(r => {
    const answer = cellHtml(r.cells?.[0])
    return `<tr><td>${esc(r.fileName)}</td>${answer}<td class="src">${esc(r.fileName)}</td></tr>`
  }).join('')
  const legend = hasAnyAmbiguity(rows)
    ? `<div class="legend">⚠ ambiguous = answer preserved as written; interpretation uncertain — review before relying on it.</div>` : ''
  const table = `<table><thead>${head}</thead><tbody>${body}</tbody></table>${legend}`
  const sub = question ? `Question: “${question}”` : `${(rows || []).length} document(s)`
  return reportShell(title || 'Bulk Q&A Report', sub, table)
}

// ── Answer Report / Contract Summary (from a chat answer + its citations) ───
export function buildAnswerReport({ title, subtitle, answerText, sources }) {
  const body = answerBodyHtml(answerText) + citationsHtml(sources)
  return reportShell(title || 'Summary', subtitle || '', body)
}

// Renders a chat answer: markdown pipe-tables become real tables; everything
// else becomes paragraphs (bold markers honored, otherwise plain text).
function answerBodyHtml(text) {
  const src = String(text || '')
  const tables = extractTables(src)
  let html = '<div class="ans">'
  if (tables.length > 0) {
    for (const t of tables) {
      html += `<table><thead><tr>${t.headers.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead>`
      html += `<tbody>${t.rows.map(r => `<tr>${r.map(c => `<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`
    }
    // Also include the prose with tables stripped, so surrounding text survives.
    const prose = src.replace(/^\s*\|.*$/gm, '').trim()
    if (prose) html += prose.split(/\n{2,}/).map(p => `<p>${inlineMd(p)}</p>`).join('')
  } else {
    html += src.split(/\n{2,}/).map(p => `<p>${inlineMd(p)}</p>`).join('')
  }
  html += '</div>'
  return html
}

// Minimal inline markdown → HTML (bold + line breaks), everything escaped first.
function inlineMd(p) {
  return esc(p).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>')
}

function citationsHtml(sources) {
  if (!Array.isArray(sources) || sources.length === 0) return ''
  const items = sources.map(s => {
    const name = typeof s === 'string' ? s : s.fileName
    const pages = (typeof s === 'object' && Array.isArray(s.pages) && s.pages.length)
      ? ` · p. ${s.pages.join(', ')}` : ''
    return `<div class="cite">${esc(name)}${esc(pages)}</div>`
  }).join('')
  return `<div class="cites"><div class="cites-h">Sources</div>${items}</div>`
}
