package com.localfilebrain.reorg;

import java.util.HashSet;
import java.util.Set;

/**
 * Extracts <i>meaningful</i> tokens from a filename — the words a human
 * would treat as semantic content, with all the noise stripped:
 *
 * <ul>
 *   <li>file extensions (jpg, pdf, …) — meaningless surface form</li>
 *   <li>common photo/screenshot prefixes (IMG, DSC, screenshot)</li>
 *   <li>dates, times, AM/PM, year-like 4-digit numbers</li>
 *   <li>pure numbers (10, 2022, 12345 …)</li>
 *   <li>single- and two-character fragments</li>
 *   <li>English stopwords</li>
 * </ul>
 *
 * <p>The point: two filenames like {@code AADHAR_FRONT_JPG.jpg} and
 * {@code Screenshot 2026-04-13 at 12.51.07 AM.png} share NO meaningful
 * tokens after this filter — even though BGE embeddings of the raw
 * strings can give spuriously high cosine similarity. We use
 * {@link #shareMeaningfulToken} as a hard pre-clustering gate on
 * filename-only-vs-filename-only pairs.
 */
public final class FilenameTokenizer {

    /**
     * English stopwords + screenshot/photo "metadata" terms that show up
     * in default filenames generated by macOS/Windows/cameras and
     * shouldn't pull files together.
     */
    private static final Set<String> NOISE_TOKENS = Set.of(
            // English stopwords likely to appear in filenames
            "the", "and", "for", "with", "from", "into", "onto", "this",
            "that", "these", "those", "your", "yours", "mine", "his",
            "her", "its", "their",
            // Time / AM-PM
            "am", "pm",
            // Photo / screenshot prefixes (always machine-generated, no semantic value)
            "img", "image", "imgs", "images", "photo", "photos", "pic",
            "pics", "picture", "pictures", "dsc", "dscn", "screenshot",
            "screenshots", "screen", "shot", "shots",
            // Document-state words common in filenames but not semantic content
            "copy", "final", "draft", "version", "untitled",
            "new", "old", "temp", "backup",
            // File extensions — leftover after the dot-strip if the filename
            // had something like "AADHAR_FRONT_JPG.jpg" (literal "JPG" in base name)
            "jpg", "jpeg", "png", "gif", "bmp", "webp", "tiff", "tif",
            "svg", "heic", "heif", "raw",
            "pdf", "doc", "docx", "txt", "md", "rtf", "odt", "pages", "epub",
            "mp3", "mp4", "mov", "wav", "avi", "mkv", "webm", "flac", "ogg",
            "zip", "rar", "tar", "gz", "tgz", "bz2", "7z",
            "ppt", "pptx", "key", "odp",
            "xls", "xlsx", "csv", "tsv", "numbers",
            "html", "htm", "css", "json", "xml", "yaml", "yml",
            "exe", "dmg", "iso", "app"
    );

    /** Minimum token length to count as meaningful. Drops noise like "v", "a1", "of". */
    private static final int MIN_TOKEN_LEN = 3;

    private FilenameTokenizer() {}

    /**
     * Returns the meaningful tokens for a filename, lowercased. Returns
     * an empty set when the filename is entirely noise (screenshots,
     * pure-numeric, single-letter prefixes etc.).
     */
    public static Set<String> meaningfulTokens(String filename) {
        if (filename == null || filename.isEmpty()) return Set.of();

        // Strip the final extension if any.
        int dot = filename.lastIndexOf('.');
        String base = (dot > 0) ? filename.substring(0, dot) : filename;

        // Split on every non-alphanumeric run, plus the digit/letter
        // boundary so "AADHAR2022" → ["AADHAR", "2022"].
        String[] raw = base.split("[^A-Za-z0-9]+|(?<=[A-Za-z])(?=\\d)|(?<=\\d)(?=[A-Za-z])");
        Set<String> out = new HashSet<>();
        for (String tok : raw) {
            String t = tok.toLowerCase();
            if (t.isEmpty()) continue;
            if (t.length() < MIN_TOKEN_LEN) continue;
            if (NOISE_TOKENS.contains(t)) continue;
            if (isPureNumber(t)) continue;       // any all-digit token
            // Distinct check for year-like 4-digit values just in case future
            // tokenizer changes make pure-number detection looser.
            if (isYearLike(t)) continue;
            out.add(t);
        }
        return out;
    }

    /**
     * True iff two filenames share at least one meaningful token. Used
     * as a HARD GATE — pairs that fail this check never form a cluster
     * edge no matter how high their embedding similarity is.
     *
     * <p>Returns false when either side has no meaningful tokens at all
     * (e.g. {@code Screenshot 2026-04-13.png} resolves to an empty set).
     * Those files become loners and go through the batched LLM judging.
     */
    public static boolean shareMeaningfulToken(String fnA, String fnB) {
        Set<String> a = meaningfulTokens(fnA);
        if (a.isEmpty()) return false;
        Set<String> b = meaningfulTokens(fnB);
        if (b.isEmpty()) return false;
        // Set intersection short-circuit
        Set<String> smaller = a.size() <= b.size() ? a : b;
        Set<String> larger  = a.size() <= b.size() ? b : a;
        for (String t : smaller) if (larger.contains(t)) return true;
        return false;
    }

    private static boolean isPureNumber(String t) {
        for (int i = 0; i < t.length(); i++) {
            if (!Character.isDigit(t.charAt(i))) return false;
        }
        return true;
    }

    private static boolean isYearLike(String t) {
        // 4-digit pure-number token in the year range we care about.
        if (t.length() != 4) return false;
        try {
            int n = Integer.parseInt(t);
            return n >= 1900 && n <= 2100;
        } catch (NumberFormatException e) {
            return false;
        }
    }
}
